/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:be09f67f-8902-4be1-93c2-6620922c6b91",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_E0uoZTQ3T",
    "aws_user_pools_web_client_id": "fdetc6buj6cd9a26o0qa3lf0m",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xf7rcwym4jaghamuxptal2pcqy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
